### ISSUE TITLE
NuGet Package SystemMonitorConfigurationAPI Version=8.84.3.11 Unavailable

### ISSUE THREAD

**Issue by qichenxu** [mat-docs/System.Monitor.Configuration.API.Client.Sample#2]
The latest commit  #1 requires **PackageReference Include="SystemMonitorConfigurationAPI" Version="8.84.3.11"**. This is unavailable from the NuGet Package Manager.

**Comment by wei-mclarenapplied** [comment]
Hi, thank you for pointing this out. We've now switched to using wildcards when referencing SystemMonitorConfigurationAPI in the example code, so it should always use the latest.

We've also pushed out a newer version of the package itself - 8.85.1.20
